micronaut:
  application:
    name: r2dbc
  metrics:
    enabled: true
r2dbc:
  datasources:
    default:
      url: r2dbc:mysql://10.110.200.78:4000/r2dbc
      username: admin
      password: bit.aim.far-211
      #schema-generate: CREATE_DROP
      dialect: MYSQL
      options:
        driver: pool
        protocol: mysql
        maxSize: 20
        initialSize: 5
        maxLifeTime: PT280S
        maxIdleTime: PT240S
        maxAcquireTime: PT6S
        poolName: r2dbc
        registerJmx: true
logger:
  levels:
    #io.r2dbc.pool: DEBUG
    #io.micronaut.data.r2dbc: DEBUG
    #reactor.pool: DEBUG