micronaut:
  application:
    name: r2dbc
  metrics:
    enabled: true
nats.addresses:
- nats://localhost:4222
r2dbc:
  datasources:
    default:
      url: r2dbc:pool:mysql://localhost:3306/db
      username: root
      password: '123'
      schema-generate: CREATE_DROP
      dialect: MYSQL
      options:
        maxSize: 20
        initialSize: 5
        maxLifeTime: PT280S
        maxIdleTime: PT240S
        maxAcquireTime: PT6S
        poolName: r2dbc
        registerJmx: true
logger:
  levels:
    #io.r2dbc.pool: DEBUG
    io.micronaut.data.r2dbc: DEBUG
    #reactor.pool: DEBUG